language: ruby
env:
  - ANSIBLE_VERSION=2.0.2
  - ANSIBLE_VERSION=2.1.6
  - ANSIBLE_VERSION=2.2.3
  - ANSIBLE_VERSION=2.3.1
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
cache: bundler
before_install:
  # make sure everything's up to date
  - sudo apt-get update -qq
  # install Python
  - sudo apt-get install python
  # upgrade pip
  - sudo pip install --upgrade pip
  # install Ansible
  - sudo pip install ansible==$ANSIBLE_VERSION
