language: ruby
env:
  - ANSIBLE_VERSION=2.0.2
  - ANSIBLE_VERSION=2.1.6
  - ANSIBLE_VERSION=2.2.3
  - ANSIBLE_VERSION=2.3.3
  - ANSIBLE_VERSION=2.4.6
  - ANSIBLE_VERSION=2.5.15
  - ANSIBLE_VERSION=2.6.19
  - ANSIBLE_VERSION=2.7.12
  - ANSIBLE_VERSION=2.8.5
rvm:
  - 2.1.10
  - 2.2.7
  - 2.3.7
  - 2.4.7
  - 2.5.6
  - 2.6.4
cache: bundler
before_install:
  # make sure everything's up to date
  - sudo apt-get update -qq
  # install Python
  - sudo apt-get install python
  # upgrade pip
  - sudo pip install --upgrade pip
  # install Ansible
  - sudo pip install ansible==$ANSIBLE_VERSION
