language: ruby
env:
  - ANSIBLE_VERSION=1.9.4
  - ANSIBLE_VERSION=2.0.0.2
rvm:
  - 2.2.4
cache: bundler
before_install:
  # make sure everything's up to date
  - sudo apt-get update -qq
  # install Python
  - sudo apt-get install python
  # upgrade pip
  - sudo pip install --upgrade pip
  # install Ansible
  - sudo pip install ansible==$ANSIBLE_VERSION