language: minimal
services:
  - docker
env:
  - ANSIBLE_VERSION=2.0.2
  - ANSIBLE_VERSION=2.1.6
  - ANSIBLE_VERSION=2.2.3
  - ANSIBLE_VERSION=2.3.3
  - ANSIBLE_VERSION=2.4.6
  - ANSIBLE_VERSION=2.5.15
  - ANSIBLE_VERSION=2.6.19
  - ANSIBLE_VERSION=2.7.12
  - ANSIBLE_VERSION=2.8.5
  - RUBY_VERSION=2.1.10
  - RUBY_VERSION=2.2.7
  - RUBY_VERSION=2.3.7
  - RUBY_VERSION=2.4.7
  - RUBY_VERSION=2.5.6
  - RUBY_VERSION=2.6.4
script:
  - docker run --rm -it -v $PWD:/app pgeraghty/ansible-ruby:$RUBY_VERSION-$ANSIBLE_VERSION /bin/sh -c cd /app && bundle install --jobs=3 --retry=3 --deployment && rake
