language: ruby
rvm:
  - 2.2.2

before_install:
  # make sure everything's up to date
  - sudo apt-get update -qq
  # install Python
  - sudo apt-get install python
  # upgrade pip
  - sudo pip install --upgrade pip
  # install Bundler
  - gem install bundler -v 1.10.5

install:
  # install Ansible
  - sudo pip install ansible
