name: Test using different Ansible & Ruby versions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ansible:
          - 2.0.2
          - 2.1.6
          - 2.2.3
          - 2.3.3
          - 2.4.6
          - 2.5.15
          - 2.6.19
          - 2.7.12
          - 2.8.5
    steps:
      - uses: actions/checkout@v1
      - name: Test against Ruby 2.6.4
        env:
          RUBY_VERSION: 2.6.4
          ANSIBLE_VERSION: ${{ matrix.ansible }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: docker run -e COVERALLS_REPO_TOKEN --rm -v $PWD:/app pgeraghty/ansible-ruby:$RUBY_VERSION-$ANSIBLE_VERSION /bin/sh -c "cd /app && bundle install --jobs=3 --retry=3 && COVERALLS_RUN_LOCALLY=true bundle exec rake"

      - name: Test against Ruby 2.5.6
        env:
          RUBY_VERSION: 2.5.6
          ANSIBLE_VERSION: ${{ matrix.ansible }}
        run: docker run --rm -v $PWD:/app pgeraghty/ansible-ruby:$RUBY_VERSION-$ANSIBLE_VERSION /bin/sh -c "cd /app && bundle install --jobs=3 --retry=3 && bundle exec rake"

      - name: Test against Ruby 2.4.7
        env:
          RUBY_VERSION: 2.4.7
          ANSIBLE_VERSION: ${{ matrix.ansible }}
        run: docker run --rm -v $PWD:/app pgeraghty/ansible-ruby:$RUBY_VERSION-$ANSIBLE_VERSION /bin/sh -c "cd /app && bundle install --jobs=3 --retry=3 && bundle exec rake"

      - name: Test against Ruby 2.3.7
        env:
          RUBY_VERSION: 2.3.7
          ANSIBLE_VERSION: ${{ matrix.ansible }}
        run: docker run --rm -v $PWD:/app pgeraghty/ansible-ruby:$RUBY_VERSION-$ANSIBLE_VERSION /bin/sh -c "cd /app && bundle install --jobs=3 --retry=3 && bundle exec rake"

      - name: Test against Ruby 2.2.7
        env:
          RUBY_VERSION: 2.2.7
          ANSIBLE_VERSION: ${{ matrix.ansible }}
        run: docker run --rm -v $PWD:/app pgeraghty/ansible-ruby:$RUBY_VERSION-$ANSIBLE_VERSION /bin/sh -c "cd /app && bundle install --jobs=3 --retry=3 && bundle exec rake"

      - name: Test against Ruby 2.1.10
        env:
          RUBY_VERSION: 2.1.10
          ANSIBLE_VERSION: ${{ matrix.ansible }}
        run: docker run --rm -v $PWD:/app pgeraghty/ansible-ruby:$RUBY_VERSION-$ANSIBLE_VERSION /bin/sh -c "cd /app && bundle install --jobs=3 --retry=3 && bundle exec rake"
