name: Test using different Ansible & Ruby versions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ansible:
          - 2.9.6
          - 2.8.10
          - 2.7.16
          - 2.6.20
          - 2.5.15
          - 2.4.6
          - 2.3.3
          - 2.2.3
          - 2.1.6
          - 2.0.2
    steps:
      - uses: actions/checkout@v1
      - name: Test against Ruby 2.7.0
        env:
          RUBY_VERSION: 2.7.0
          ANSIBLE_VERSION: ${{ matrix.ansible }}
        run: >
          docker run --rm -v $PWD:/app pgeraghty/ansible-ruby:$RUBY_VERSION-$ANSIBLE_VERSION
          /bin/sh -c "cd /app && bundle install --jobs=3 --retry=3 &&
          COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_REPO_TOKEN }} COVERALLS_RUN_LOCALLY=true bundle exec rake"

      - name: Test against Ruby 2.6.5
        env:
          RUBY_VERSION: 2.6.5
          ANSIBLE_VERSION: ${{ matrix.ansible }}
        run: >
          docker run --rm -v $PWD:/app pgeraghty/ansible-ruby:$RUBY_VERSION-$ANSIBLE_VERSION
          /bin/sh -c "cd /app && bundle install --jobs=3 --retry=3 && bundle exec rake"

      - name: Test against Ruby 2.5.7
        env:
          RUBY_VERSION: 2.5.7
          ANSIBLE_VERSION: ${{ matrix.ansible }}
        run: >
          docker run --rm -v $PWD:/app pgeraghty/ansible-ruby:$RUBY_VERSION-$ANSIBLE_VERSION
          /bin/sh -c "cd /app && bundle install --jobs=3 --retry=3 && bundle exec rake"

      - name: Test against Ruby 2.4.9
        env:
          RUBY_VERSION: 2.4.9
          ANSIBLE_VERSION: ${{ matrix.ansible }}
        run: >
          docker run --rm -v $PWD:/app pgeraghty/ansible-ruby:$RUBY_VERSION-$ANSIBLE_VERSION
          /bin/sh -c "cd /app && bundle install --jobs=3 --retry=3 && bundle exec rake"

      - name: Test against Ruby 2.3.7
        env:
          RUBY_VERSION: 2.3.7
          ANSIBLE_VERSION: ${{ matrix.ansible }}
        run: >
          docker run --rm -v $PWD:/app pgeraghty/ansible-ruby:$RUBY_VERSION-$ANSIBLE_VERSION
          /bin/sh -c "cd /app && bundle install --jobs=3 --retry=3 && bundle exec rake"

      - name: Test against Ruby 2.2.7
        env:
          RUBY_VERSION: 2.2.7
          ANSIBLE_VERSION: ${{ matrix.ansible }}
        run: >
          docker run --rm -v $PWD:/app pgeraghty/ansible-ruby:$RUBY_VERSION-$ANSIBLE_VERSION
          /bin/sh -c "cd /app && bundle install --jobs=3 --retry=3 && bundle exec rake"

      - name: Test against Ruby 2.1.10
        env:
          RUBY_VERSION: 2.1.10
          ANSIBLE_VERSION: ${{ matrix.ansible }}
        run: >
          docker run --rm -v $PWD:/app pgeraghty/ansible-ruby:$RUBY_VERSION-$ANSIBLE_VERSION
          /bin/sh -c "cd /app && bundle install --jobs=3 --retry=3 && bundle exec rake"
